### ISSUE TITLE
Documentation example not working on latest version, datasets are always undefined

### ISSUE THREAD

**Issue by tiagog000** [SalesforceLabs/LightningWebChartJS#10]
I've been trying out this app by installing directly on a sandbox from appexchange (Versionv1.1.0 / 1.1.0) however
when I deployed the latest master (today) to a scratch org it seems to have stopped working properly.

Using the same example on the documentation:

**Example for Line**

Inputs: 
- Type-> line
- Dataset Labels -> ["Label 1","Label 2"]
- Dataset -> [{"label":"Data 1", "detail":[1, 1]},{"label":"Data 2", "detail":[2, 2]}]

Result:
Dataset labels are always undefined but graph is accurate
<img width="624" alt="Image 2020-09-16 at 2 53 25 PM" src="https://user-images.githubusercontent.com/5667142/93347245-c1afe100-f82c-11ea-9381-09c901f6e4eb.png">

Expected:
Dataset labels appear correct and graph are render properly.

**Example for Radar**

Inputs: 
- Type-> radar
- Dataset Labels -> ["Label 1","Label 2"]
- Dataset -> [{"label":"Data 1", "detail":[1, 1]},{"label":"Data 2", "detail":[2, 2]}]

Result:
Dataset labels are always undefined and radar graph is not accurate
<img width="643" alt="Image 2020-09-16 at 2 57 55 PM" src="https://user-images.githubusercontent.com/5667142/93347978-95e12b00-f82d-11ea-809d-9c7b241c7136.png">

Expected:
Dataset labels appear correct and graph are render properly.

**Comment by scolladon** [comment]
Hi @tiagog000 

Latest version contains the fix (v1.2.0)
The appexchange is going to be updated soon

Be carefull ! There is a breaking change. explained in the [release note](https://github.com/SalesforceLabs/LightningWebChartJS/releases/tag/v1.2.0)

Have fun !
