### ISSUE TITLE
Charts do not load when Lightning Web Security is enabled

### ISSUE THREAD

**Issue by b1t4c0r4** [SalesforceLabs/LightningWebChartJS#129]
## _Who_ is the bug affecting?
to all environments in which the Lightning Web Security option is activated

## _What_ is affected by this bug?
could not load the charts

## _When_ does this occur?
always

## _Where_ on the platform does it happen?
all pages

## _How_ do we replicate the issue?

Go to Setup / Session Settings / enable check "Use Lightning Web Security for Lightning web components (GA) and Aura components (Beta) " and Save.

## Expected behavior (i.e. solution)

check the compatibility according to the documentation

https://developer.salesforce.com/docs/component-library/documentation/en/lwc/security_lwsec_intro

## Other Comments
I am reviewing this in my current project, if I have it before, I can contribute to the community.

**Comment by victorgz** [comment]
Hello @b1t4c0r4 , unfortunately the library is not compatible with LWS.
You can find the details in [our doc](https://salesforcelabs.github.io/LightningWebChartJS/docs/general/faq.html#:~:text=Does%20LWCC%20work%20with%20Lightning%20Web%20Security%20(LWS)%3F).
