### ISSUE TITLE
Stack bar chart with managed package

### ISSUE THREAD

**Issue by fkramer690** [SalesforceLabs/LightningWebChartJS#132]
Hey team, 

I am trying to group a SOQL, so that the format fits for a stacked bar chart. Can you please provide me an example how to do it to get a result like this one:

![image](https://user-images.githubusercontent.com/87364496/235787444-027bfcf1-bf28-4ac3-a971-28a92a96eaa1.png)

I am fine with all sobjects.

Thank you very much

Fabian

**Comment by scolladon** [comment]
Hi @fkramer690 !

I think you are looking for this [part of the doc](https://salesforcelabs.github.io/LightningWebChartJS/#:~:text=Focus%20on%20the%20%22SOQL%22%20Property).

Let me know if it helps.
