### ISSUE TITLE
How to replace axis numbers by labels ? (+ extra-rerender issue in managed package)

### ISSUE THREAD

**Issue by nvuillam** [SalesforceLabs/LightningWebChartJS#133]
Hi, thanks again for this component that we're about to release on an AppExchange in a Managed Package that will be demo-ed at the World Tour Paris next week :)

We only have 2 issues:

1. Is there a way to replace axis number by labels ?

On the following image we would like to replace 0 , 1 , 2, 3 by none, weak, medium, strong

![image](https://github.com/SalesforceLabs/LightningWebChartJS/assets/17500430/1778ec1d-0282-4f1b-a65d-5d2e93f41681)

2. We use "easeInSine" animation

In a scratch, no problem, everytime we click on a column, the "grow up" animation is not triggered again
But with the same code embedded within a managed package, the "grow up" animation is triggered sometimes twice or 3 times everytime the value of the chart changes, have you already seen that ?

(As it is client proprietary code I can't share all code but I'll be glad to make a call if you think it can help )

```
                <lightning-layout-item size="6" large-device-size="6" small-device-size="8">
                    <c-chart lwc:ref="c-chart" type="bar" events='["click"]' callback-click={handleChartClick}
                        stylecss="position: relative; margin: auto;" data-x={selectedAgreementCategory}>
                        <c-dataset labels={columnsAsString}>
                            <c-data detail={graphDataAsString} backgroundcolor={columnsBackground}
                                bordercolor={columnsBorder} borderwidth="1">
                            </c-data>
                        </c-dataset>
                        <c-title text="Obligations conventionnelles"></c-title>
                        <c-animation duration="500" easing="easeInSine"> </c-animation>
                        <c-cartesian-linear-axis ticks-suggestedmax="3" ticks-suggestedmin="0"
                            ticks-stepsize="1"></c-cartesian-linear-axis>
                        <c-tooltip enabled="false"></c-tooltip>
                    </c-chart>
                </lightning-layout-item>
```

**Comment by scolladon** [comment]
Hi @nvuillam !

Nice to ear you like the product and you will use it with a customer 🙏 
We can't wait to see that live!

Here is our answers with @victorgz 
1. We don't know ChartJs library in detail but we think you could address your need with [this](https://salesforcelabs.github.io/LightningWebChartJS/docs/api/axes.html#:~:text=the%20chart%20area.-,ticksCallback,-function) part of the doc.
2. It does not ring a bell. It would require a more in-depth investigation to understand what is driving the lib to behaves this way in different contexts (scratch vs sandbox vs prod, namespace, LWS, feature activated, etc)

Let us know if it helps!

**Comment by nvuillam** [comment]
@scolladon many thanks for the quick reply :)

I'll try with ticksCallback , and about the other issue ... after newest version of the package has been installed, no more blinking without reason... so not reproducible, all good :)

I'll let you know here if i succeed about ticksCallback so it can hel others !

**Comment by nvuillam** [comment]
Working ! :)

For anyone interested:

```html
                        <c-cartesian-linear-axis ticks-suggestedmax="3" ticks-suggestedmin="0"
                            ticks-stepsize="1" ticks-callback={handleTicksCallback}></c-cartesian-linear-axis>
```

```javascript
    columnLabels = {
        0: 'inexistant',
        1: 'faible',
        2: 'moyen',
        3: 'fort'
    }

    handleTicksCallback = (value) => {
        return this.columnLabels[value] || "inconnu";
    }
```

![image](https://github.com/SalesforceLabs/LightningWebChartJS/assets/17500430/2e736b2a-7a26-4c16-a4a4-c64e2f2b29a8)


@scolladon @victorgz many thanks for the great support :)
