### ISSUE TITLE
Not able to successfully populate the RADAR chart using SOQL query

### ISSUE THREAD

**Issue by alicewix** [SalesforceLabs/LightningWebChartJS#19]
## _Who_ is the bug affecting?

The new feature we are going to deploy is not yet affecting users as it is not yet available in Prod.

## _What_ is affected by this bug?

Not having charts displayed correctly.

## _When_ does this occur?

not applicable - as we were not able to have the issue fixed yet.

## _Where_ on the platform does it happen?

In the Radar Chart from the component included on one of out Lightning Pages in Salesforce.

## _How_ do we replicate the issue?

We are trying to configure and set up the Radar Chart by using SOQL Query, but probably our query is not correctly created.
Query: 
SELECT  ID  label , 
SUM(Pain_number__c ), SUM(Collaborate_number__c),  SUM(Power_number__c),  SUM(Value_number__c),  SUM(Vision_number__c),  SUM(CRTA_number__c)  value 
FROM Sales_Check__c  
 WHERE Opportunity__c = '0065800000CHsdHAAT' 
WITH SECURITY_ENFORCED GROUP BY ID LIMIT 10

Currently the Chart is displaying the following image:
![image](https://user-images.githubusercontent.com/72221186/94842987-b65fd680-0424-11eb-94a9-5613ea5b4e07.png)

## Expected behavior (i.e. solution)

By using Dataset Property, the chart is correctly displaying the chart:
Dataset:
[{"label":"12/08/2020","detail":[5,2,5,2,3,4]},
{"label":"11/09/2020","detail":[1,1,1,2,5,0]},
{"label":"12/08/2020","detail":[0,1,3,6,3,4]}]

Dataset Labels:
["Collaborate","CRTA","Pain","Value","Vision","Power"]
![image](https://user-images.githubusercontent.com/72221186/94843225-122a5f80-0425-11eb-9841-25508891d221.png)

## Other Comments
Can you please at least help us with a SOQL example for RADAR Charts, similar to the one from your website, but applicable for Radar?
SELECT StageName label, SUM(Amount) value FROM Opportunity WHERE IsClosed = false WITH SECURITY_ENFORCED GROUP BY StageName LIMIT 10

**Comment by victorgz** [comment]
Hi @alicewix ,

Unfortunately, the **radar, scatter and bubble charts are not supported in the SOQL Chart Builder version yet**. These three types of chart need more axis dimensions to be displayed, and that is something that we don't handle for this specific scenario. We've discussed with the team and we don't plan to include it in the short-term backlog.

However, you can create the radar chart using a custom LWC (and just map the result of your query to match the supported structure by the chart). You can see an example in our [samples gallery](https://salesforcelabs.github.io/LightningWebChartJS/docs/general/samples.html).

We're going to update the documentation to make it clear, as we know it can lead to confusion.

I hope this can help, and thanks for reaching us !

**Comment by alicewix** [comment]
Thanks a lot @victorgz  for all the details!
It really makes sense now.

Wish you a great day ahead.
Alice

**Comment by scolladon** [comment]
@victorgz Just to right my thoughts

I think we could achieve to do it if we group by another field and if we use naming convention to understand that we are using another field to sub group.

Something like :
```
SELECT Sum(Amount) value, Stage label, AccountId subgrouping from Opportunity Where Stage = 'stage'  WITH SECURITY ENFORCED  group by Stage, AccountId limit 1000
```
Then we can create an array of array to in the aChartData.detail in the SOQLDataProvider.
Then we need to structure the this_detail property to have x.detail equals an array of integer from that to display.

It could be an approach, let's keep it in mind
