### ISSUE TITLE
No MODULE found in LWC

### ISSUE THREAD

**Issue by lsaggu** [SalesforceLabs/LightningWebChartJS#22]
## _Who_ is the bug affecting?

All Supervisors

## _What_ is affected by this bug?

Unable to include any LWCC chart in a LWC.

## _When_ does this occur?

Every time I attempt to deploy my LWC containing LWCC markup:
`

        
        <div class="slds-grid">
            
            <div class="slds-col slds-size_1-of-1 slds-large-size_6-of-12">
                
                <c-chart type="bar">
                    <c-title text="TEST"></c-title>
                    <c-legend position="bottom"></c-legend>
                </c-chart>
            </div>
            
            <div class="slds-col slds-size_1-of-1 slds-large-size_6-of-12">
                
            </div>
        </div>

`

## _Where_ on the platform does it happen?

I'm attempting to deploy a component that will be shown on a Lightning App Page

## _How_ do we replicate the issue?

1. Install the LWCC package in a sandbox
2. Create a Lightning Web Component (LWC)
3. Add simple LWCC Markup to the LWC:
`<c-chart type="bar">
                    <c-title text="TEST"></c-title>
                    <c-legend position="bottom"></c-legend>
                </c-chart>`

## Expected behavior (i.e. solution)

The component should deploy to the sandbox with the LWCC markup

## Other Comments

I may be missing something very simple, but I am not sure what. Please advise.

**Comment by victorgz** [comment]
Hi @lsaggu ,
Can you please give us the exact error you get when you try to deploy your component including LWCC?

Meanwhile, some things to check:
1. Make sure that the package is installed correctly (you can see if it appears in Setup > Apps > Packaging > Installed Packages) 
2. See if the problem could be related to your namespace. Enable My Domain and deploy it to the users (https://help.salesforce.com/articleView?id=sfdx_dev_reg_namespace.htm&type=5 - step 2)

Thanks !

**Comment by lsaggu** [comment]
Hi @victorgz ,
Thanks for your response. The exact error is as follows:

**Comment by victorgz** [comment]
Hi @lsaggu ,

I've just managed to reproduce the error in a clean sandbox from my side and found the problem! I don't know why I didn't see it before.

You're using a managed packaged version (installed from the appExchange) what means, that the components belongs to a specific namespace. So instead of including them with the default namespace (c-) you need to append their specific one. In our case, the namespace is `lwcc`:

![Screenshot 2020-10-20 at 20 09 11](https://user-images.githubusercontent.com/6944989/96627276-e9550600-1310-11eb-89b8-8707b0bb2464.png)

Just include LWCC inside your component as below:
```
<lwcc-chart type="bar">
        <lwcc-title text="TEST"></lwcc-title>
        <lwcc-legend position="bottom"></lwcc-legend>
 </lwcc-chart>
```

We know that this can be kind of confusing, as our documentation is doing reference to the open source version with the examples. We will update it to make it more clear.

Hope this works for you and thanks for reaching us !

**Comment by lsaggu** [comment]
@victorgz - I actually gave that a try, but I see the following error when trying to load the page with the component:

> Attempting to reference cross-namespace module lwcc-chart in c-scheduledJobsCharts

Are you able to reproduce this? Or is there something else that I'm missing?

**Comment by victorgz** [comment]
@lsaggu actually there's nothing that you're missing. This is a known [limitation of LWC](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/create_components_namespace): _"A custom Lightning web component can’t access a Lightning web component or module in a custom namespace."_

If you're a developer, I would suggest you to clone the repository, include it inside your project and deploy the components. You can then use your custom namespace (__c by default) and you will be able to include the charts inside your LWCs. You can even have both options installed in your org: the managed packaged for the App Builder version, and the SFDX for the developer experience.

We hope that the platform will remove that limitation one day, but for now it is out of our scope. From our side, we're reviewing also the possibility to transform this managed package into unmanaged (so we wouldn't have the namespace problem anymore). But still to be reviewed and confirmed.

Thanks !

**Comment by lsaggu** [comment]
Thanks @victorgz - I'll see about cloning the repository and using the regular namespace. I appreciate you looking into this for me.

**Comment by matthewglong** [comment]
"we're reviewing also the possibility to transform this managed package into unmanaged"
That would be very much appreciated! Or split this module in two -- a managed side for the Admin LWCC and an unmanaged for custom dev.

**Comment by scolladon** [comment]
you're right @matthewglong and you actually can have the unmanaged source, you just have to deploy [force-app/main/default](https://github.com/SalesforceLabs/LightningWebChartJS/tree/master/force-app/main/default)
