### ISSUE TITLE
Test error: testGetDataWithDateLabel fails after deployment to a production org.

### ISSUE THREAD

**Issue by troveryor** [SalesforceLabs/LightningWebChartJS#33]
## _Who_ is the bug affecting?
Anyone with automation that modifies Opportunity CloseDate values.

## _What_ is affected by this bug?
Test failures that impede deployment and changesets

## _When_ does this occur?
On all test runs of SOQLDataProviderTest.testGetDataWithDateLabel() in an org that has automation that modifies CloseDate values oncreate. For instance, this was not an issue in a scratch org without any automation on this field.

## _Where_ on the platform does it happen?
Testing tools including during deployment and changesets

## _How_ do we replicate the issue?
Create an org with any kind of automation that modifies the CloseDate on creation of an Opportunity.
Run SOQLDataProviderTest.testGetDataWithDateLabel() and observe a message like this in the logs:
   ```
 System.AssertException: Assertion Failed: 
    chartDatas.label must equals 2021-03-28 00:00:00: 
                       Expected: (2021-03-28 00:00:00), 
                       Actual:   (2021-04-06 00:00:00)
```

## Expected behavior (i.e. solution)
Test should pass even in the presence of automation on the CloseDate field.

## Other Comments
One solution would be to query for the Opportunity record created in that test record, or a testSetup() function. Then use the field value for the assert.

**Comment by victorgz** [comment]
Hi @troveryor, thanks for finding the issue and suggesting a solution!

Effectively, we were using kind of static values so the automations would make it fail. We're going to change it to make it relative to the org where the package is installed.

Btw, you were just in time! We're about to release a new version and this fix will be included on it 🚀

**Comment by troveryor** [comment]
Yeah, that's usually about my timing for bug finding ha ha!
Great news, thanks @victorgz
