### ISSUE TITLE
Option to choose the display units & show axis values

### ISSUE THREAD

**Issue by Raja1461** [SalesforceLabs/LightningWebChartJS#41]
really liked  this.. would love to see if there any option to choose the display units for number/currency fields and show axis values in report chart settings.

![image](https://user-images.githubusercontent.com/55504044/113537890-7af2c000-959f-11eb-9c2f-287619e7bdda.png)

**Comment by victorgz** [comment]
Hi @Raja1461 ,

The Chart Builder solution aims to provide a very general usage of the charts. Your suggestion sounds good, but it is a very specific scenario, so it doesn't fit in the Chart Builder concept. We're not planning to include this in our roadmap for now.

You can, however, build this solution using the developer edition, creating your custom chart and converting the values following your own rules to display them in the axis. You can have a look to our [sample gallery](https://sfdc.co/lwcc) to see different examples of custom charts and to the FAQ to see how to interact with JS callbacks.

Thanks !
