### ISSUE TITLE
Formatting Y axis

### ISSUE THREAD

**Issue by andrewdourado** [SalesforceLabs/LightningWebChartJS#42]
I'm using LWCC and I need to format its Y axis like

1000 to 1K
2000 to 2K
1000000 to 1M

Is it possible?

In ChartJS I found these solutions:
[Chart.js - Formatting Y axis](https://stackoverflow.com/questions/20371867/chart-js-formatting-y-axis)
[y axis Formatting with Metric prefix 1000=> 1k Chart.js](https://stackoverflow.com/questions/44606556/y-axis-formatting-with-metric-prefix-1000-1k-chart-js)

**Comment by victorgz** [comment]
Hi @andrewdourado !

Yes, you can format the axis using the ticksCallback property of the axis component (https://salesforcelabs.github.io/LightningWebChartJS/docs/api/axes.html). This property exposes the callback you're expecting from your examples:
```
ticks: {
                    callback: function(label, index, labels) {
                        return label/1000+'k';
                    }
                }
```

You can have a look also to our [FAQ](https://salesforcelabs.github.io/LightningWebChartJS/docs/general/faq.html), to see how to implement a callback function with LWCC.

Hope this helps, and thanks for reaching out !

**Comment by andrewdourado** [comment]
It's working. Thanks @victorgz!
