### ISSUE TITLE
Multiple axes with different scales is not supported? But its mentioned in the documentation

### ISSUE THREAD

**Issue by nehanagori** [SalesforceLabs/LightningWebChartJS#48]
## _Who_ is the bug affecting?

All Supervisors

## _What_ is affected by this bug?

Analysis 

## _When_ does this occur?

when try to add another axixs to the chart 

As per documentation --
Axis ID
The properties xaxisid and yaxisid from the Data component have to match the scale propertie id of the specific axis type. This is especially needed if multi-axes charts are used.

Creating Multiple Axes
With cartesian axes, it is possible to create multiple X and Y axes. To 

## _Where_ on the platform does it happen?

on any lwc component with chart

## _How_ do we replicate the issue?

just add two axis component with ids and map it to the data

## Expected behavior (i.e. solution)

Multiple axis should have shown

## Other Comments

Do you have a sample that works?

**Comment by victorgz** [comment]
Hi @nehanagori,

We've exposed the Chart.js functionality to work with multiple axis, but we don't have any example at the moment.
Unfortunately, I've tried to create one and it seems that we might have a bug regarding this topic. We will have a look at it and will let you know.

fyi @scolladon I think we've a bug on the chartServiceConfig module. The merge of axis when they are of the same type is not working correctly. Also, we're exposing the `id` attribute and it seems that this is a reserved property, so the value is being overwritten. I will work on a fix for that 🚧

**Comment by nehanagori** [comment]
Yes you are right, Id attribute is reserved. I even tried to change that in js of the component ,  but that was not enough. Looking forward for the fix from you :)

**Comment by victorgz** [comment]
Hi @nehanagori ,
This issue should have been fixed now 😄 
You can take the last commit of the master branch and integrate it in your project. We've also included a new example in the [sample gallery](https://salesforcelabs.github.io/LightningWebChartJS/docs/general/samples.html), don't hesitate to have a look and try it by yourself. We would love to hear any feedback from your 🚀 
![image](https://user-images.githubusercontent.com/6944989/117052617-4007b780-ad18-11eb-886f-ed6654a85dd2.png)
