### ISSUE TITLE
:recordId in Community Page

### ISSUE THREAD

**Issue by steverichardson** [SalesforceLabs/LightningWebChartJS#7]
Any known issues with displaying a LWCC chart in a community page? My app builder solution works in a standard platform record page but the same solution (SOQL) does not display data in a community record page. It appears to be related to the :recordId parameter not being passed from community record page to the component.

**Comment by victorgz** [comment]
Hi @steverichardson , thanks for having indentified and reported the bug!

We have included the fix in our latest relase (v1.2.0), so you can already clone the repository to use it.
For the AppExchange, the new version will be updated soon.

Have fun !

**Comment by steverichardson** [comment]
Thank you, Victor. I'll look forward to the AppExchange package version update.
