### ISSUE TITLE
Label position wrong with multiple instances of builder

### ISSUE THREAD

**Issue by peterbaeza** [SalesforceLabs/LightningWebChartJS#70]
## _When_ does this occur?

When two builder instances are put on the same page and have differing legend positions the position of the last loaded instance will be used for all instances upon after refresh.

## _Where_ on the platform does it happen?

Both on LEX pages and on Community pages. 

## _How_ do we replicate the issue?

Create two instances of a builder on the same page. Select diferent legend positions. Save the page and refresh.

## Expected behavior (i.e. solution)

Each instance should have the assigned position for that instance..

**Comment by victorgz** [comment]
Hi @peterbaeza , sorry for the late reply, we've been quite busy lately.

I've reviewed the problem and effectively there was an issue with the legend and multiple instances of the chart. We've prepared a fix for that and we will release a new version soon.

Thanks for using the solution !
