### ISSUE TITLE
Apex Custom data provider not working

### ISSUE THREAD

**Issue by mmzoughi90** [SalesforceLabs/LightningWebChartJS#74]
Hi,

I have this custom data provider that I use in a Lightning page just to test showing a pie chart with the lightning component and the apex custom data provider and I have an error:
**The apex class:**
public without sharing class AP18_TSCustomPieDataProvider extends lwcc.ChartDataProvider {
    public Object initParameter;
    public override void init(final Object initParameter) {
    }
    public override List<lwcc.ChartDataProvider.ChartData> getData() {
        final List<lwcc.ChartDataProvider.ChartData> chartDatas = new List<lwcc.ChartDataProvider.ChartData>();
        lwcc.ChartDataProvider.ChartData aChartData = new lwcc.ChartDataProvider.ChartData();
        aChartData.labels = DEMO_LABEL;
        aChartData.detail = DEMO_DATA;
        aChartData.bgColor = DEMO_COLOR;
        chartDatas.add(aChartData);
        return chartDatas;
    }

    public static final List<String> DEMO_LABEL = new List<String>{'Test1','Test2'};
    public static final List<Decimal> DEMO_DATA = new List<Decimal>{
            10,
            20
    };
    public static final String DEMO_COLOR = 'rgba(0,0,0,0.5);';
}

And the error message is: "Attempt to de-reference a null object"

## _How_ do we replicate the issue? = it happend always

Thanks,

**Comment by Mock1** [comment]
I also can't get the above, or the demo sample in the repository, to work.

**Comment by victorgz** [comment]
Hi @Mock1 and @mmzoughi90. I've been able to reproduce the error from my side too and I am now working to look for an explanation and a fix for it.

Meanwhile, there is one workaround that seems to work: change the access modifier of the class extending `lwcc.ChartDataProvider` to `global`. In the example above it would be: `global without sharing class AP18_TSCustomPieDataProvider extends lwcc.ChartDataProvider { ... }`. You can keep `public` access level in the methods.

Can you please let me know if this works for you? Thanks !

**Comment by Mock1** [comment]
Maybe @mmzoughi90  can test the global edit. I was able to narrow it down to just the managed package, and I suspect it's tied into the namespace. I also put a debug statement in the init method, and it never fired, so I think the ChartBuilderController is failing to fetch the class.
I uninstalled the package, and just deployed the code here unmanaged, and it suddenly works.  But sadly, now I can't test the edit suggested.

I think that checks out with the public->global change, I don't think the package can "see" the class without it being global.

**Comment by eclarke12** [comment]
> Hi @Mock1 and @mmzoughi90. I've been able to reproduce the error from my side too and I am now working to look for an explanation and a fix for it.
> 
> Meanwhile, there is one workaround that seems to work: change the access modifier of the class extending `lwcc.ChartDataProvider` to `global`. In the example above it would be: `global without sharing class AP18_TSCustomPieDataProvider extends lwcc.ChartDataProvider { ... }`. You can keep `public` access level in the methods.
> 
> Can you please let me know if this works for you? Thanks !

Thanks for this, global access modifier worked for me too.
