### ISSUE TITLE
Support for Drilldown Chart

### ISSUE THREAD

**Issue by ybbhosale** [SalesforceLabs/LightningWebChartJS#84]
## _Who_ is the bug affecting?
Who wants to build drill-down chart behavior . It is a suggestion you should implement 

Allow User to capture Click Event and it should give where is clicked this way developer can draw another chart giving Drill down Effect

**Comment by victorgz** [comment]
Hi @ybbhosale , this is already possible. In fact LWCC is just a wrapper for the Chart.js library, and they already have the ability to do that (even if it is not very intuitive IMHO).

So I was looking around and I found this [Stackoverflow article](https://stackoverflow.com/questions/37122484/chart-js-bar-chart-click-events) where someone found how to do that in the native library. Basically, you need to capture the click event, call the `getElementAtEvent` method of the chart and from the results you can extract the index of the dataset and the data value where there user clicked.

**Note:** I've just seen that [we actually expose](https://github.com/SalesforceLabs/LightningWebChartJS/blob/b0c1d3fdd0d3e532377bea3fb2d31304e594f05e/force-app/main/default/lwc/chart/chart.js#L261) the `getElementAtEvent` wrapper in our library, but we forgot to include it in the documentation. We will update it soon.

Meanwhile, here you have a quick working example to capture which element the user clicked on:

```html
<template>
	<div class="slds-card">
		<c-chart type="line" responsive="true" callback-click={handleCallbackClick}>
			<c-dataset labels='["January", "February", "March", "April", "May", "June", "July"]'>
				<template for:each={datasets} for:item="dataset">
					<c-data key={dataset.label} label={dataset.label} detail={dataset.detail} bordercolor={dataset.bordercolor} fill="false"></c-data>
				</template>
			</c-dataset>
		</c-chart>
	</div>
</template>
```

```js
import { LightningElement } from 'lwc';

export default class TestChart extends LightningElement {
	_chart;

	datasets = [
		{ label: "First dataset", detail: [ 10, 30, 46, 2, 18, 50, 0 ], bordercolor: "rgba(119, 185, 242, 1)" },
		{ label: "Second dataset", detail: [ 15, 25, 49, 24, 5, 15, 20 ], bordercolor: "rgba(225, 96, 50, 1)" }
	]

	renderedCallback() {
		if ( this._init )
			return;
		this._chart = this.template.querySelector( 'c-chart' );
	}

	handleCallbackClick = ( evt ) => {
		const elementsAtEvent = this._chart.getElementAtEventChart( evt );
		if ( elementsAtEvent.length > 0 ) {
			const datasetIndex = elementsAtEvent[ 0 ]._datasetIndex;
			const detailIndex = elementsAtEvent[ 0 ]._index;
			console.log( `Clicked on: ${this.datasets[ datasetIndex ].detail[ detailIndex ]}` );
		} else {
			console.log( 'Not clicked on a chart detail point' );
		}
	}
}
```
I hope this helps, and thanks for using the library !

**Comment by vyomtrainers** [comment]
Thanks A lot for Detail
