### ISSUE TITLE
ticksSuggestedmax works only one time after chart rendering

### ISSUE THREAD

**Issue by npolozyuk** [SalesforceLabs/LightningWebChartJS#85]
I'm using horizontal bar chart with dynamic ticks-suggestedmax, which means that ticks-suggestedmax is calculated accordingly received data details. For the first time chart and cartesian-linear-axis were built correctly, after second time changing data: data details were updated but ticks-suggestedmax was not. For some reason it doesn't go for listenerHandlers function. Can you please have a look to this issue.

**Comment by victorgz** [comment]
Hi @npolozyuk , thanks for using the library. Could you please share with us the code of your horizontal bar? It will help us to investigate faster the issue. Thanks !

**Comment by victorgz** [comment]
Quick update: I've tried to reproduce the problem and seems to be working for me (quick & dirty example):

```html
<lightning-button onclick={changeData} label="Change data"></lightning-button>

<c-chart type="horizontalBar">
	<c-dataset labels='["Eating", "Drinking", "Sleeping", "Designing", "Coding", "Cycling", "Running"]'>
		<c-data label="My dataset" detail={data} backgroundcolor="rgba(255, 176, 59, 1)"></c-data>
	</c-dataset>
	<c-title text="Radar Chart"></c-title>
	<c-cartesian-category-axis axis="y" position="left"></c-cartesian-category-axis>
	<c-cartesian-linear-axis axis="x" ticks-suggestedmax="200" tick-min="10"></c-cartesian-linear-axis>
</c-chart>
```

```js
import { LightningElement } from 'lwc';

export default class Example extends LightningElement {

	data = [28, 48, 40, 19, 96, 27, 100];

	changeData(){
		if(this.data[0] < 500){
			this.data = [800, 500, 750, 190, 910, 270, 100];
		}else{
			this.data = [28, 48, 40, 19, 96, 27, 100];
		}
	}
}
```
First rendering, low values and suggested max = 200:
![image](https://user-images.githubusercontent.com/6944989/153043904-b5e28d5f-c980-430e-abbf-ec0ccfac5a90.png)

After clicking on the button, we get high values so the suggested max value is ignored (values are higher than 200):
![image](https://user-images.githubusercontent.com/6944989/153044060-824b98e5-c900-4182-9487-98d7b47b8ae3.png)

**Comment by npolozyuk** [comment]
Hi @victorgz. It's not exactly the case, ticks-suggestedmax is supposed to be dynamic. I modified a little bit your code example.
<lightning-button onclick={changeData} label="Change data"></lightning-button>

<c-chart type="horizontalBar">
	<c-dataset labels='["Eating", "Drinking"]'>
		<c-data label="My dataset" detail={data} backgroundcolor="rgba(255, 176, 59, 1)"></c-data>
	</c-dataset>
	<c-title text="Radar Chart"></c-title>
	<c-cartesian-category-axis axis="y" position="left"></c-cartesian-category-axis>
	<c-cartesian-linear-axis axis="x" ticks-suggestedmax={maxticks} tick-min="10"></c-cartesian-linear-axis>
</c-chart>

import { LightningElement } from 'lwc';

export default class Example extends LightningElement {

	data = [70, 50];
        render = false;

	changeData(){
		 this.render = !this.render;
	         this.data = this.render === true ? [30, 20] : [70, 50] ;
	}
        
         get maxticks() {
           return Math.max(...this.data) + (Math.max(...this.data) * 0.1); 
        }
}

If you try this example, you will see that x-axis is the same, what is not right.

**Comment by npolozyuk** [comment]
Hi @victorgz. The problem is fixed and chart works great.  Thank you for your help!
