### ISSUE TITLE
Graph Showing Axis with huge number sometime not readable 

### ISSUE THREAD

**Issue by vyomtrainers** [SalesforceLabs/LightningWebChartJS#88]
## _Who_ is the bug affecting?
![image](https://user-images.githubusercontent.com/93213458/149778964-c4db1735-ac26-4bb2-aea8-464bea278dd5.png)
You can View the graph it is showing numbers from 500000 to 4000000 When such big numbers displayed on screen user take time to think over and required time to understand 

My Question is Can we display numbers like 400K or 4M

**Comment by victorgz** [comment]
Hi @vyomtrainers , this is already possible with the library.
You just need to need call the [ticksCallback function](https://salesforcelabs.github.io/LightningWebChartJS/docs/api/axes.html) of your axis, and then format the values as you want. One quick example here:

```html
<c-chart type="line" responsive="true">
  <c-dataset labels='["Item 1","Item 2","Item 3","Item 4", "Item 5","Item 6","Item 7"]'>
    <c-data label="Neutral" detail="[400000, 470000, 440000, 380000, 270000, 310000, 250000]" bordercolor='rgba(50, 150, 237, 1)'></c-data>
  </c-dataset>
  <c-cartesian-axis axis="y" ticks-callback={handleTicksCallback}></c-cartesian-axis>
</c-chart>
```

And then in your controller:
```js
handleTicksCallback(value) {
  return Number(value).toLocaleString() + "€";
}
```

![image](https://user-images.githubusercontent.com/6944989/150383683-3d0f9cc4-5842-425f-bd1a-a70828b50637.png)
